### PR TITLE
bugfix: vendor depedendency mismatch

### PR DESCRIPTION
**Pull request by cyx**
## Rationale

Doing a `go get` yields an error, as follows:

```
$ go get -u github.com/emicklei/proto-contrib/cmd/protofmt
# github.com/emicklei/proto-contrib/cmd/protofmt
proto-contrib/cmd/protofmt/main.go:93:44: cannot use def (type *"github.com/emicklei/proto-contrib/cmd/protofmt/vendor/github.com/emicklei/proto".Proto) as type *"github.com/emicklei/proto".Proto in argument to protofmt.NewFormatter(output, "  ").Format
```
## Changelog

- Moves the vendor folder to the root of the project.

### CODE REVIEW

**Comment by amerine** [comment]
@cyx Nice.

**Comment by emicklei** [comment]
what is happening here? My intension was for each command to have it own vendored packages. Apparently, that does not work (for you).

**Comment by cyx** [comment]
Are you able to make it work locally? I tried it also with go1.9 and same result. My understanding is that the vendor folder is causing issues.

**Comment by emicklei** [comment]
i reverted the change and will not proceed with vendoring. Instead, I will setup a Travis CI build job to verify the tools

**Pull request closed without merging**
